on:
  pull_request:
    types:
      - opened
      - reopened
      - labeled
      - synchronize
    branches:
      - $default-branch

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write
  deployments: write

name: Integration

jobs:
  lint:
    name: Integrate
    uses: dudo-home-lab/.github/.github/workflows/lint.yaml@main

  test:
    name: Integrate
    uses: dudo-home-lab/.github/.github/workflows/test.yaml@main

  deploy:
    if: github.event.action == 'labeled' && github.event.label.name == 'preview' || github.event.action == 'synchronize' && contains(github.event.pull_request.labels.*.name, 'preview')
    name: Deploy
    uses: dudo-home-lab/.github/.github/workflows/deploy.yaml@main
    with:
      environment: preview

  build:
    needs: deploy
    name: Build
    uses: dudo-home-lab/.github/.github/workflows/build.yaml@main
