# https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions
# https://docs.github.com/en/repositories/releasing-projects-on-github/about-releases
# https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication#using-the-github_token-in-a-workflow

on:
  workflow_call:

permissions:
  contents: write

name: Release Repository

jobs:
  release:
    name: ${{ github.repository }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gitops-ci-cd/.github/actions/release@main
        with:
          sha: ${{ github.sha }}
